apiVersion: v1
kind: Namespace
metadata:
  name: private
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: private
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: nginx:alpine
          # imagePullPolicy: Never
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: dashboard
   namespace: private
spec:
  rules:
  - host: application.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: my-service
            port:
              number: 80
