apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"application","namespace":"private"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"application"}},"template":{"metadata":{"labels":{"app":"application"}},"spec":{"containers":[{"image":"app:latest","name":"application","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2023-10-30T18:10:15Z"
  generation: 3
  name: application
  namespace: private
  resourceVersion: "25554"
  uid: c6f88d49-5505-40f0-901c-2f01e96de9c2
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: application
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: application
    spec:
      containers:
      - image: app:latest
        imagePullPolicy: Always
        name: application
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-10-30T18:10:15Z"
    lastUpdateTime: "2023-10-30T18:10:15Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-10-30T18:10:15Z"
    lastUpdateTime: "2023-10-30T18:23:41Z"
    message: ReplicaSet "application-6fb85b8b8" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 3
  replicas: 4
  unavailableReplicas: 4
  updatedReplicas: 1
