name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project
  two:
    needs : one
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project
  artifacts:
    needs: two
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello, world!" > Log.txt
      - name:  artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: file
          path: |
            Log.txt
  deploy: 
    needs: artifacts
    runs-on: ubuntu-latest
    steps:
      - name:  artifacts
        uses: actions/download-artifact@v3
        with: 
          name: file
      - name: list
        run: ls
      
  
